gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    doctrine_mappings: true # Permite mapear los tokens en Doctrine
    user_provider: App\Security\UserProvider # Ajusta esto si es necesario
    manager_type: doctrine
    ttl: 31536000 # Expiración del Refresh Token en segundos (1 año)