nelmio_cors:
    defaults:
        allow_credentials: true  # Permite credenciales (cookies, cabeceras de autorización, etc.)
        allow_origin: ['http://localhost:4200']  # Origen exacto de tu frontend (debe coincidir con la URL del frontend)
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null  # Aplica la configuración a todas las rutas
