nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # Aquí usas una variable de entorno
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null  # Aplica la configuración a todas las rutas
