FROM php:8.2-apache

# Instalar dependencias necesarias para pdo_pgsql y Composer
RUN apt-get update && apt-get install -y \
    curl \
    libpq-dev \
    gcc \
    make \
    autoconf \
    libc-dev \
    pkg-config \
    unzip \
    git \
    openssl \
    apache2-utils

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Instalar las extensiones necesarias de PHP
RUN docker-php-ext-install pdo pdo_pgsql

# Habilitar los módulos de Apache necesarios para CORS, reescritura de URL y SSL
RUN a2enmod rewrite headers ssl

# Copiar archivos de la aplicación al contenedor
COPY . /var/www/html/

# Copiar certificados SSL al contenedor
COPY ./apache/ssl/mysite.crt /etc/ssl/certs/mysite.crt
COPY ./apache/ssl/mysite.key /etc/ssl/private/mysite.key

# Crear y dar permisos al directorio de datos para imágenes y otros archivos
RUN mkdir -p /var/www/html/data && chown -R www-data:www-data /var/www/html/data

# Copiar la configuración personalizada de Apache
COPY ./apache/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf

# Habilitar los sitios
RUN a2ensite 000-default.conf default-ssl.conf

# Exponer los puertos 80 y 443 para la aplicación web
EXPOSE 80 443

# Iniciar Apache en primer plano
CMD ["apache2-foreground"]
