version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./data:/var/www/html/data

    depends_on:
      - db
    ports:
      - "8080:80"  # Exponer el puerto correctamente

  db:
    image: postgres:15  # Imagen oficial de PostgreSQL
    container_name: symfony_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"  # Exponer el puerto para la conexión
    volumes:
      - db_data:/var/lib/postgresql/data  # Montaje correcto del volumen

  pgadmin:
    image: dpage/pgadmin4  # Imagen oficial de pgAdmin
    container_name: symfony_pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"  # Exponer pgAdmin en el puerto 8081
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - ./pgAdmin:/var/lib/pgadmin

volumes:
  db_data:
