# Dockerfile actualizado para PHP 8.2
FROM php:8.2-apache

# Instalar dependencias necesarias para pdo_pgsql y Composer
RUN apt-get update && apt-get install -y \
    curl \
    libpq-dev \
    gcc \
    make \
    autoconf \
    libc-dev \
    pkg-config \
    unzip \
    git

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Instalar las extensiones necesarias de PHP
RUN docker-php-ext-install pdo pdo_pgsql

# Habilitar la extensión pdo_pgsql en el archivo php.ini
RUN echo "extension=pdo_pgsql.so" > /usr/local/etc/php/conf.d/30-pdo_pgsql.ini

# Copiar archivos de la aplicación al contenedor
COPY . /var/www/html/

# Exponer el puerto 80 para la aplicación web
EXPOSE 80

# Iniciar Apache en primer plano
CMD ["apache2-foreground"]